extends RefCounted
## Baked, authored face variants for the shared infantry rig.
##
## Heads are generated by the offline character builder and stored in the packed
## character scenes. The eye openings, eyelid rims, eyeballs, irises and pupils are
## separate geometry; only subtle skin detail remains shader-driven.

const HEAD_BONE := 4

static func variant_count() -> int:
	return 3

static func build(variant_index: int = 0) -> ArrayMesh:
	var data: Dictionary = _variant(variant_index)
	var mesh := ArrayMesh.new()
	var skin := SurfaceTool.new()
	skin.begin(Mesh.PRIMITIVE_TRIANGLES)
	_build_shell(skin, data)
	_build_eyelids(skin, data)
	_build_ears(skin, data)
	skin.generate_normals()
	skin.index()
	skin.set_material(_skin_material(data))
	skin.commit(mesh)

	var sclera := SurfaceTool.new()
	sclera.begin(Mesh.PRIMITIVE_TRIANGLES)
	var iris := SurfaceTool.new()
	iris.begin(Mesh.PRIMITIVE_TRIANGLES)
	var pupil := SurfaceTool.new()
	pupil.begin(Mesh.PRIMITIVE_TRIANGLES)
	for side: float in [-1.0, 1.0]:
		_build_eye(sclera, iris, pupil, side, data)
	for surface: SurfaceTool in [sclera, iris, pupil]:
		surface.generate_normals()
		surface.index()
	sclera.set_material(_eye_material(Color(0.38, 0.34, 0.29), 0.34))
	iris.set_material(_eye_material(data.iris, 0.38))
	pupil.set_material(_eye_material(Color(0.018, 0.014, 0.011), 0.24))
	sclera.commit(mesh)
	iris.commit(mesh)
	pupil.commit(mesh)
	return mesh

static func _variant(index: int) -> Dictionary:
	var variants: Array[Dictionary] = [
		{
			"name": "square",
			"width": 1.00, "depth": 1.00, "jaw": 1.08,
			"eye_x": 0.0315, "eye_y": 1.646, "eye_tilt": -0.0005,
			"nose_length": 0.034, "nose_width": 1.03, "mouth_y": 1.580,
			"asymmetry": 0.012, "ear_scale": 1.0,
			"skin": Color(0.58, 0.425, 0.325), "iris": Color(0.18, 0.27, 0.30),
			"stubble": 0.12, "freckles": 0.10
		},
		{
			"name": "long",
			"width": 0.94, "depth": 1.02, "jaw": 0.92,
			"eye_x": 0.030, "eye_y": 1.650, "eye_tilt": 0.0012,
			"nose_length": 0.038, "nose_width": 0.92, "mouth_y": 1.578,
			"asymmetry": -0.016, "ear_scale": 0.94,
			"skin": Color(0.51, 0.365, 0.275), "iris": Color(0.23, 0.31, 0.20),
			"stubble": 0.20, "freckles": 0.04
		},
		{
			"name": "broad",
			"width": 1.055, "depth": 0.97, "jaw": 1.02,
			"eye_x": 0.033, "eye_y": 1.644, "eye_tilt": -0.0014,
			"nose_length": 0.032, "nose_width": 1.08, "mouth_y": 1.583,
			"asymmetry": 0.019, "ear_scale": 1.06,
			"skin": Color(0.65, 0.475, 0.355), "iris": Color(0.25, 0.20, 0.13),
			"stubble": 0.07, "freckles": 0.16
		}
	]
	return variants[posmod(index, variants.size())]

static func _profile(t: float, data: Dictionary) -> Vector2:
	# Deliberately authored facial planes: chin, jaw angle, cheekbone, brow, temple,
	# cranium and crown. These proportions replace the previous egg-like shell.
	var rings: Array[Vector2] = [
		Vector2(0.030, 0.034), Vector2(0.044, 0.055),
		Vector2(0.059, 0.071), Vector2(0.067, 0.078),
		Vector2(0.075, 0.084), Vector2(0.073, 0.082),
		Vector2(0.075, 0.086), Vector2(0.076, 0.087),
		Vector2(0.071, 0.084), Vector2(0.060, 0.074),
		Vector2(0.041, 0.052), Vector2(0.002, 0.003)
	]
	var at: float = clampf(t, 0.0, 1.0) * float(rings.size() - 1)
	var i: int = mini(int(at), rings.size() - 2)
	var profile: Vector2 = rings[i].lerp(rings[i + 1], smoothstep(0.0, 1.0, at - i))
	var jaw_influence: float = 1.0 - smoothstep(0.22, 0.48, t)
	profile.x *= float(data.width) * lerpf(1.0, float(data.jaw), jaw_influence)
	profile.y *= float(data.depth)
	return profile

static func _head_point(t: float, angle: float, data: Dictionary) -> Vector3:
	var y: float = lerpf(1.505, 1.765, t)
	var profile: Vector2 = _profile(t, data)
	var x: float = cos(angle) * profile.x
	var side_bias: float = 1.0 + float(data.asymmetry) * (-1.0 if x < 0.0 else 1.0)
	x *= side_bias
	var z: float = sin(angle) * profile.y - 0.010
	if sin(angle) < -0.18:
		var front: float = smoothstep(0.18, 0.86, -sin(angle))
		var eye_x: float = float(data.eye_x)
		var eye_y: float = float(data.eye_y)
		var nose_scale: float = float(data.nose_width)
		var sockets: float = _bump(absf(x), y, eye_x, eye_y, 0.020, 0.014) * 0.013
		var brow: float = _bump(absf(x), y, eye_x, eye_y + 0.016, 0.025, 0.009) * 0.006
		var bridge: float = _bump(x, y, 0.0, 1.630, 0.012 * nose_scale, 0.045) * float(data.nose_length) * 0.52
		var tip: float = _bump(x, y, 0.0, 1.604, 0.018 * nose_scale, 0.021) * float(data.nose_length) * 0.66
		var wings: float = _bump(absf(x), y, 0.014 * nose_scale, 1.599, 0.010, 0.010) * 0.005
		var cheeks: float = _bump(absf(x), y, 0.047 * float(data.width), 1.618, 0.026, 0.020) * 0.010
		var muzzle: float = _bump(x, y, 0.0, float(data.mouth_y) + 0.008, 0.030, 0.018) * 0.002
		var chin: float = _bump(x, y, 0.0, 1.550, 0.034, 0.019) * 0.014
		z += (sockets - brow - bridge - tip - wings - cheeks - muzzle - chin) * front
	return Vector3(x, y, z)

static func _build_shell(st: SurfaceTool, data: Dictionary) -> void:
	var rings := 44
	var sides := 64
	for ring: int in range(rings):
		for side: int in range(sides):
			for corner: Vector2i in [Vector2i(0, 0), Vector2i(1, 0), Vector2i(1, 1), Vector2i(0, 0), Vector2i(1, 1), Vector2i(0, 1)]:
				var t: float = float(ring + corner.y) / float(rings)
				var angle: float = float(side + corner.x) * TAU / float(sides)
				_add(st, _head_point(t, angle, data), Vector2(float(side + corner.x) / float(sides), t))

static func _front_point(x: float, y: float, data: Dictionary) -> Vector3:
	var t: float = clampf(inverse_lerp(1.505, 1.765, y), 0.0, 1.0)
	var width: float = _profile(t, data).x
	var angle: float = TAU - acos(clampf(x / maxf(width, 0.001), -0.98, 0.98))
	return _head_point(t, angle, data)

static func _build_eyelids(st: SurfaceTool, data: Dictionary) -> void:
	var segments := 20
	for side: float in [-1.0, 1.0]:
		var center := Vector2(side * float(data.eye_x), float(data.eye_y) + side * float(data.eye_tilt))
		for segment: int in range(segments):
			var a0: float = float(segment) * TAU / float(segments)
			var a1: float = float(segment + 1) * TAU / float(segments)
			var outer0 := center + Vector2(cos(a0) * 0.0175, sin(a0) * 0.0085)
			var outer1 := center + Vector2(cos(a1) * 0.0175, sin(a1) * 0.0085)
			var inner0 := center + Vector2(cos(a0) * 0.0105, sin(a0) * 0.0038)
			var inner1 := center + Vector2(cos(a1) * 0.0105, sin(a1) * 0.0038)
			var p_outer0: Vector3 = _front_point(outer0.x, outer0.y, data) - Vector3(0, 0, 0.0005)
			var p_outer1: Vector3 = _front_point(outer1.x, outer1.y, data) - Vector3(0, 0, 0.0005)
			var p_inner0: Vector3 = _front_point(inner0.x, inner0.y, data) - Vector3(0, 0, 0.0020)
			var p_inner1: Vector3 = _front_point(inner1.x, inner1.y, data) - Vector3(0, 0, 0.0020)
			for point: Vector3 in [p_outer0, p_inner0, p_inner1, p_outer0, p_inner1, p_outer1]:
				_add(st, point, Vector2(point.x * 5.0 + 0.5, inverse_lerp(1.505, 1.765, point.y)))

static func _build_ears(st: SurfaceTool, data: Dictionary) -> void:
	var scale: float = float(data.ear_scale)
	for side: float in [-1.0, 1.0]:
		var center := Vector3(side * 0.076 * float(data.width), 1.632, 0.002)
		_ellipsoid(st, center, Vector3(0.012, 0.026, 0.015) * scale, 12, 8)

static func _build_eye(sclera: SurfaceTool, iris: SurfaceTool, pupil: SurfaceTool, side: float, data: Dictionary) -> void:
	var center_y: float = float(data.eye_y) + side * float(data.eye_tilt)
	var face: Vector3 = _front_point(side * float(data.eye_x), center_y, data)
	var center := Vector3(face.x, center_y, face.z + 0.0045)
	_ellipsoid(sclera, center, Vector3(0.0110, 0.0065, 0.0095), 18, 10)
	# Pull the colored discs just ahead of the curved sclera. A sub-millimeter
	# separation was lost to depth precision at normal gameplay distances.
	var iris_center := Vector3(center.x, center.y, center.z - 0.0115)
	_disc(iris, iris_center, 0.0040, 18)
	_disc(pupil, iris_center + Vector3(0, 0, -0.00045), 0.00175, 16)

static func _ellipsoid(st: SurfaceTool, center: Vector3, radius: Vector3, segments: int, rings: int) -> void:
	for ring: int in range(rings):
		for segment: int in range(segments):
			for corner: Vector2i in [Vector2i(0, 0), Vector2i(1, 0), Vector2i(1, 1), Vector2i(0, 0), Vector2i(1, 1), Vector2i(0, 1)]:
				var v: float = float(ring + corner.y) / float(rings)
				var u: float = float(segment + corner.x) / float(segments)
				var latitude: float = lerpf(-PI * 0.5, PI * 0.5, v)
				var longitude: float = u * TAU
				var point := center + Vector3(cos(latitude) * cos(longitude) * radius.x, sin(latitude) * radius.y, cos(latitude) * sin(longitude) * radius.z)
				_add(st, point, Vector2(u, v))

static func _disc(st: SurfaceTool, center: Vector3, radius: float, segments: int) -> void:
	for segment: int in range(segments):
		var a0: float = float(segment) * TAU / float(segments)
		var a1: float = float(segment + 1) * TAU / float(segments)
		for point: Vector3 in [center, center + Vector3(cos(a1) * radius, sin(a1) * radius, 0), center + Vector3(cos(a0) * radius, sin(a0) * radius, 0)]:
			_add(st, point, Vector2(0.5 + (point.x - center.x) / (radius * 2.0), 0.5 + (point.y - center.y) / (radius * 2.0)))

static func _add(st: SurfaceTool, point: Vector3, uv: Vector2) -> void:
	st.set_uv(uv)
	st.set_bones(PackedInt32Array([HEAD_BONE, 0, 0, 0]))
	st.set_weights(PackedFloat32Array([1.0, 0.0, 0.0, 0.0]))
	st.add_vertex(point)

static func _skin_material(data: Dictionary) -> ShaderMaterial:
	var material := ShaderMaterial.new()
	material.shader = load("res://shaders/face_surface.gdshader")
	material.set_shader_parameter("skin_tone", data.skin)
	material.set_shader_parameter("eye_height", data.eye_y)
	material.set_shader_parameter("mouth_height", data.mouth_y)
	material.set_shader_parameter("stubble_strength", data.stubble)
	material.set_shader_parameter("freckle_strength", data.freckles)
	return material

static func _eye_material(color: Color, roughness: float) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = color
	material.roughness = roughness
	material.cull_mode = BaseMaterial3D.CULL_DISABLED
	return material

static func _bump(x: float, y: float, cx: float, cy: float, sx: float, sy: float) -> float:
	return exp(-pow((x - cx) / sx, 2.0) - pow((y - cy) / sy, 2.0))

static func remove_donor_head(mesh: ArrayMesh) -> ArrayMesh:
	var arrays: Array = mesh.surface_get_arrays(0)
	var points: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
	var indices: PackedInt32Array = arrays[Mesh.ARRAY_INDEX]
	var kept := PackedInt32Array()
	for triangle: int in range(0, indices.size(), 3):
		if minf(points[indices[triangle]].y, minf(points[indices[triangle + 1]].y, points[indices[triangle + 2]].y)) > 1.505:
			continue
		kept.append_array(indices.slice(triangle, triangle + 3))
	arrays[Mesh.ARRAY_INDEX] = kept
	var result := ArrayMesh.new()
	result.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return result
